from typing import Any, Callable, Generic, ParamSpec, TypeVar, TypeVarTuple
from autohotpy.static_typing.classes import Bool, BoolInt
from autohotpy.static_typing.classes.object_ import Object

class Func:
    def __call__(self, *args: Any) -> Any: ...
    def Bind(self, *params: Any) -> BoundFunc: ...
    def IsByRef(self, index=..., /) -> BoolInt: ...
    def IsOptional(self, index=..., /) -> BoolInt: ...

    Name: str
    IsBuiltIn: Bool
    IsVariadic: Bool
    MinParams: int
    MaxParams: int

class BoundFunc(Func): ...
class Closure(Func): ...
class Enumerator(Func): ...
