from typing import Concatenate, overload
from autohotpy.proxies.var_ref import VarRef
from autohotpy.static_typing.classes import Bool, BoolInt
from autohotpy.static_typing.classes.object_ import Object

class Func[**Params, Ret](Object):
    def __call__(self, /, *args: Params.args, **_: Params.kwargs) -> Ret: ...
    @overload
    def Bind(
        self, /, *params: Params.args, **_: Params.kwargs
    ) -> BoundFunc[[], Ret]: ...
    @overload
    def Bind(self, /, *params) -> BoundFunc[..., Ret]: ...
    def IsByRef(self, index: int = ..., /) -> BoolInt: ...
    def IsOptional(self, index: int = ..., /) -> BoolInt: ...

    Name: str
    IsBuiltIn: Bool
    IsVariadic: Bool
    MinParams: int
    MaxParams: int

class BoundFunc[**Params, Ret](Func[Params, Ret]): ...
class Closure[**Params, Ret](Func[Params, Ret]): ...
class Enumerator[P1, P2](Func[[VarRef[P1], VarRef[P2]], BoolInt]): ...
